스택(괄호)
nerdchanii/Algorithm_study pull request #16
Opened 2021-09-12 11:10 UTC by yureka0920

## 푼 문제: 스택(괄호)
### 문제: [문제이름](링크)
https://www.acmicpc.net/problem/9012
### 담당리뷰어
-  reviewer :

### 특이사항

2021-09-12 11:20 UTC, yureka0920 reviewed
백준은 처음이라 미완성인 코드를 올렸습니다. 
리뷰어분께 죄송하지만 부족한 부분에 대해서, 혹은 틀렸다고 생각되는 부분에 대해서 집중적으로 리뷰 부탁드릴게요!

2021-09-13 05:17 UTC, vg-rlo commented on code/junho/stack1.py
> +        if string[i]=='(':
저 같은 경우에 (를 pop하거나 append 하는 방식으로 구성했는데, 
stack 이라는 int 변수로 계산한 점이 좀더 간단해보이네요 
아무래도 리스트 연산보다 속도 측면에서도 빠를 거 같아요 👍

2021-09-13 05:22 UTC, vg-rlo requested changes

2021-09-13 05:22 UTC, vg-rlo commented on code/junho/stack1.py
> +        if(i+1==len(string) and stack==0):
if 조건문에 판별문을 for문 바깥쪽으로 빼면 정상적으로 동작할거 같아요! 
((()())) 이렇게 안쪽에서 괄호가 닫히고 바깥쪽 괄호가 감싸는 형태로 입력이 들어가는 경우를 고려해보면 for문 안쪽에 있는 경우에 대해 에러가 발생할거 같습니다. 
+1, -1 연산으로 전체 string 입력에 대해 진행해준후에, if문으로 stack의 값이나, string 리스트의 길이에 따라 판별해주는 걸 시도해보세요!

코드 상에서 if문 쪽에서
`if i+1==len(string)` 부분에서 판별문에서 좌측은 주로 변수로 두고, 우측을 어떤 연산 결과를 두는 경향이 있기 때문에, `if i==len(string)-1`으로 수정하면 좋을거 같습니다! 고생하셨습니다!

2021-09-13 14:05 UTC, yureka0920 commented on code/junho/stack1.py
> +        if(i+1==len(string) and stack==0):
말씀해주신 사항을 반영하여 코드를 수정하였습니다. 세심한 코드리뷰 너무나도 감사드려요!
질문사항이 있습니다. 백준은 처음 풀어보는데, 파이썬으로 코드를 제출할때 이번에 수정한 것 처럼 함수를 정의해서 제출하면 되는건가요? 자꾸 틀렸다고 뜨는데 프로그래머스 와는 달리 print를 찍어볼수도 없어서 디버깅이 어렵네요 ㅠㅠ

2021-09-13 14:08 UTC, yureka0920 commented on code/junho/stack1.py
> +        if string[i]=='(':
감사합니다 ㅠㅠ 많이 부족하지만 앞으로 더 발전하고 싶어요!

2021-09-13 14:08 UTC, merged